
name: CI


on:
  push:
    branches: [ master ]
  


jobs:

  build:
   
    runs-on: ubuntu-latest

   
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v1.0.1
      with:
        version: 0.13.0

    # Runs a set of commands using the runners shell
    - name: Terraform Init & Validate
      run: |
        terraform init
        terraform validate