
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
 
  build:
    
    runs-on: ubuntu-latest

   
    steps:
   
    - uses: actions/checkout@v2
    
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v1.0.1
      with:
        version: 0.13.0

    
    - name: Terraform Init & Validate
      run: |
        terraform init
        terraform validate